os: linux
language: node_js
cache: npm

jobs:
  include:
    - stage: build-js
      node_js: lts/*
      script:
        - npm run build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t $DOCKER_USER/image-processor:$TRAVIS_COMMIT .
        - docker push $DOCKER_USER/image-processor:$TRAVIS_COMMIT
